### ISSUE TITLE
Waste collector "meerlanden" not found! after upgrade from 5.0.2 to 5.0.3

### ISSUE THREAD

**Issue by HoekieN** [pippyn/Home-Assistant-Sensor-Afvalbeheer#342]
Hi, after upgrading to 5.0.3 Afvalbeheer is not working anymore for me and i get the following error in the log.

Logger: homeassistant.helpers.entity
Source: custom_components/afvalbeheer/API.py:148
Integration: Afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 6:22:43 PM (8 occurrences)
Last logged: 6:24:13 PM

Update for sensor.meerlanden_gft fails
Update for sensor.meerlanden_restafval fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 180, in update
    collection = self.data.collections.get_first_upcoming_by_type(self.waste_type)
  File "/config/custom_components/afvalbeheer/API.py", line 148, in collections
    return self.collector.collections
AttributeError: 'NoneType' object has no attribute 'collections'

**Comment by HoekieN** [comment]
Logger: homeassistant
Source: custom_components/afvalbeheer/API.py:133
Integration: Afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 6:22:19 PM (1 occurrences)
Last logged: 6:22:19 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/API.py", line 133, in async_update
    await self.collector.update()
AttributeError: 'NoneType' object has no attribute 'update'

**Comment by ronaldt80** [comment]
Same issue, rolling back to 5.0.2 solves the error

**Comment by gkappen** [comment]
Same issue here, also rolled back to 5.0.2

**Comment by andyfsimon** [comment]
Confirmed too.

**Comment by ookonbekend** [comment]
Same issue here, rolling back to 5.0.2 solves the error also

**Comment by keesg60** [comment]
Also the same issue here, rolled back to 5.0.2
wastecollector: Circulus

**Comment by pippyn** [comment]
Can someone please share their config of the platform in a DM the HA forum with me? Including their address

I'll write a fix tomorrow!

**Comment by HoekieN** [comment]
> Can someone please share their config of the platform in a DM the HA forum with me? Including their address
> 
> I'll write a fix tomorrow!

I have send you a DM on HA with my config

**Comment by pippyn** [comment]
Thank you @HoekieN!
The issue should be fixed in v5.0.4, can you please confirm?

I'm so sorry for introducing this bug

**Comment by HoekieN** [comment]
No problem.

Thanks it works again :)
